(()=>{'use strict';const $=id=>document.getElementById(id);let step=0,outcome='ask',timer=null;const scenes=[
{chapter:'先接住你的交辦',title:['一句交辦，','開始一段','合作。'],description:'你說要什麼，他先確認要交出什麼。',speaker:'你',avatar:'你',context:'今天 09:00 · 工作交辦',dialogue:'「下午開會，幫我準備最新的銷售報表。」',reply:'Kai：好，我會確認最新資料，整理好交給你。',clock:'09:00',status:'準備接手',presence:'Kai 在這裡',thought:'下午開會用的報表',mechanism:'先建立這件工作的共同脈絡',technical:'使用者交辦後，保存交付內容、資料範圍與責任。這是本情境的工作契約，不只是回一句「收到」。',flow:['交辦','確認交付內容','保留責任'],evidence:['team',0]},
{chapter:'記得回來，不用你再提醒',title:['時間到了，','他記得','回來看。'],description:'「下午要用的資料，現在進度怎麼樣？」',speaker:'Kai',avatar:'K',context:'今天 10:00 · 開始一次查看',dialogue:'「該確認報表的進度了，先看最新資料。」',reply:'這一輪先做事；有需要，才打擾你。',clock:'10:00',status:'想起待辦',presence:'開始查看進度',thought:'下午會議快到了',mechanism:'執行機會來自時間、事件或接續',technical:'本幕使用排程到期作為例子。新訊息、工作完成等事件也能啟動工作；正在執行的迴圈可以直接接續。',flow:['時間 / 事件','載入工作脈絡','開始回合'],evidence:['agent',0]},
{chapter:'先看事實，再決定要不要問',title:['先查一下，','現在到了','哪一步。'],description:'讀取資料與之前的對話，不只盯著截止時間。',speaker:'Kai',avatar:'K',context:'今天 10:01 · 查看工作來源',dialogue:'「報表還沒找到。Alex 上次說，整理後會傳給我。」',reply:'沒找到完成證據，先確認狀況，不直接認定對方沒做。',clock:'10:01',status:'查看資料',presence:'正在確認最新資訊',thought:'資料與承諾對得上嗎？',mechanism:'觀察工具、記憶與工作狀態一起使用',technical:'資料來源需要事先接好並取得授權。讀取原始資料與跟進紀錄，才能判斷這次是否有新變化。',flow:['來源工具','近期脈絡','最新工作狀態'],evidence:['agent',1]},
{chapter:'找對人，用一句話接上',title:['需要的時候，','他會主動','問一句。'],description:'交代背景與需要的結果，讓對方容易接手。',speaker:'Kai → Alex',avatar:'K',context:'今天 10:02 · 跟進資料',dialogue:'「Alex，想確認銷售報表的進度，下午開會會用到。」',reply:'這則追問送出後，留下等待狀態，不重複催問。',clock:'10:02',status:'確認進度',presence:'正在與 Alex 協作',thought:'確認交付時間',mechanism:'模型判斷與對外發話分開',technical:'在授權範圍內選擇詢問、交付或等待。後台查看不代表每次都要發訊息，送出也不代表工作已完成。',flow:['判斷值得介入','確認對象與授權','發話 / 保持安靜'],evidence:['agent',3]},
{chapter:'等到回覆，接著把事情做完',title:['對方一回覆，','工作就能','接下去。'],description:'接回同一件事，保留背景，不用你重新交辦。',speaker:'Alex → Kai',avatar:'A',context:'今天 10:15 · 收到回覆',dialogue:'「最新版整理好了，檔案給你。這次是九月資料。」',reply:'Kai：收到，我會確認期間與內容，再整理成會議版本。',clock:'10:15',status:'整理報表',presence:'正在接回這件工作',thought:'確認版本與內容',mechanism:'回覆事件恢復等待中的工作',technical:'將新回覆連回原任務，保留 owner、資料版本與等待條件。這裡示範的是本專案交接契約，不是宣稱所有框架都有相同資料模型。',flow:['回覆到來','找到等待中的工作','恢復處理'],evidence:['team',3]},
{chapter:'有成果，也有交代',title:['把成果交給你，','也記住這件事','完成了。'],description:'交付可用的內容，附上來源，關閉這次跟進。',speaker:'Kai → 你',avatar:'K',context:'今天 10:20 · 工作交付',dialogue:'「報表整理好了。資料期間已標明，來源也附在裡面。」',reply:'你拿到成果；他留下完成證據，下次不再追同一件事。',clock:'10:20',status:'已交付',presence:'這件事，有結果了',thought:'工作已完成',mechanism:'完成證據、工作狀態與送達各自記錄',technical:'交付後保留成果與來源；確認工作是否完成，與訊息是否送達是不同的判斷。這是我們提出的工作閉環與驗收要求。',flow:['成果與來源','交付結果','完成 / 等待狀態'],evidence:['agent',4]}
];
function effective(){const s={...scenes[step]};if(outcome==='deliver'&&step>=2){if(step===2){s.dialogue='「最新版已在資料夾裡，期間與這次會議需要相符。」';s.reply='既然資料已齊，就不必再向 Alex 追問。';s.thought='資料已經齊了';}if(step===3){Object.assign(s,{title:['資料已經齊了，','就直接','往下做。'],description:'省掉多餘的追問，把時間用在整理成果。',dialogue:'「資料完整，我直接整理會議版本。」',reply:'有完成證據就推進工作，不機械式催進度。',status:'直接整理',presence:'沒有多餘的打擾',thought:'直接準備交付'});}if(step===4){Object.assign(s,{speaker:'Kai',avatar:'K',context:'今天 10:05 · 準備成果',dialogue:'「內容與來源已確認，準備交付。」',reply:'同一件事往下做，不需要等待一則多餘的回覆。',title:['確認資料，','把成果','整理好。'],clock:'10:05'});}}
if(outcome==='wait'&&step>=2){if(step===2){s.dialogue='「剛剛已經問過 Alex，現在還沒有新回覆。」';s.reply='確認已問過，避免再發同一則訊息。';}if(step>=3){Object.assign(s,{title:['剛剛才問過，','這次先','不打擾。'],description:'知道什麼時候等待，也是合作的一部分。',speaker:'Kai',avatar:'K',context:'今天 10:02 · 保留等待',dialogue:'「沒有新消息，先繼續等回覆。」',reply:'保留這件工作。有新回覆或到下一次查看時間，再接續。',clock:'10:02',status:'等待回覆',presence:'安靜等待，不重複催問',thought:'已問過 · 等待 Alex',mechanism:'等待仍然是一個有記錄的工作狀態',technical:'沒有新變化時保留等待條件與來源；不把每次喚醒都轉成通知，也不把等待誤記為完成。',flow:['已追問的紀錄','沒有新變化','等待下一個機會'],evidence:['agent',4]});}}
return s;}
function stop(){clearInterval(timer);timer=null;$('play-day').querySelector('span').textContent=step===5?'重看這段合作':'看他怎麼工作';}
function setText(id,text){$(id).textContent=text;}
function render(){const s=effective();const title=$('scene-title');const accent=document.createElement('span');accent.textContent=s.title[2];title.replaceChildren(document.createTextNode(s.title[0]),document.createElement('br'),document.createTextNode(s.title[1]),accent);for(const [id,value]of Object.entries({'chapter-number':String(step+1).padStart(2,'0'),'chapter-label':s.chapter,'scene-description':s.description,'speaker-avatar':s.avatar,'speaker-name':s.speaker,'speaker-context':s.context,dialogue:s.dialogue,reply:s.reply,'scene-clock':s.clock,'person-status':s.status,'presence-label':s.presence,'thought-title':s.thought,'mechanism-heading':s.mechanism,'mechanism-copy':s.technical}))setText(id,value);$('scene-shell').dataset.scene=step;$('scene-shell').dataset.outcome=outcome;$('alex-message').textContent=step===4?'最新版整理好了，這次是九月資料。':'收到，稍後把最新版給你。';$('result-title').textContent=step===5?'會議報表已交付':'銷售報表';$('result-subtitle').textContent=step===4?'九月版本 · 正在確認':'已整理 · 附上資料來源';$('mini-mechanism').replaceChildren(...s.flow.flatMap((text,i)=>{const item=document.createElement('span');item.textContent=text;if(!i)return[item];const arrow=document.createElement('i');arrow.textContent='→';return[arrow,item];}));const ev=window.VISUAL_EVIDENCE[s.evidence[0]][s.evidence[1]];setText('evidence-type',ev.type);setText('evidence-claim',ev.claim);setText('evidence-limit',ev.limit);$('evidence-links').replaceChildren(...ev.sources.map(([label,href])=>{const a=document.createElement('a');a.href=href;a.textContent=label+' ↗';return a;}));const sourcebox=$('dialog-evidence');sourcebox.replaceChildren();for(const id of ['evidence-type','evidence-claim','evidence-links','evidence-limit']){const node=$(id).cloneNode(true);node.removeAttribute('id');sourcebox.append(node);}document.querySelectorAll('[data-step]').forEach(b=>{const n=Number(b.dataset.step);if(n===step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');b.classList.toggle('past',n<step);});document.querySelectorAll('button[data-outcome]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.outcome===outcome)));document.body.classList.remove('changed');void document.body.offsetHeight;document.body.classList.add('changed');$('next-scene').firstChild.textContent=step===5?'回到開始 ':'下一幕 ';if(!timer)stop();}
function advance(){step=(step+1)%6;render();}
$('play-day').addEventListener('click',()=>{if(timer){stop();document.body.classList.add('paused-motion');return;}document.body.classList.remove('paused-motion');if(matchMedia('(prefers-reduced-motion: reduce)').matches){advance();return;}if(step===5){step=0;render();}timer=setInterval(()=>{step++;render();if(step===5)stop();},4500);$('play-day').querySelector('span').textContent='暫停故事';});$('next-scene').addEventListener('click',()=>{stop();document.body.classList.remove('paused-motion');advance();});document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{stop();step=Number(b.dataset.step);render();}));document.querySelectorAll('button[data-outcome]').forEach(b=>b.addEventListener('click',()=>{stop();outcome=b.dataset.outcome;step=2;render();}));const dialog=$('source-dialog');$('sources-open').addEventListener('click',()=>{stop();dialog.showModal();$('sources-close').focus();});$('sources-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>$('sources-open').focus());document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();document.body.classList.add('paused-motion');}else document.body.classList.remove('paused-motion');});document.addEventListener('keydown',e=>{if(dialog.open||e.altKey||e.ctrlKey||e.metaKey||e.target.closest('button,a,input,textarea,summary'))return;if(e.key==='ArrowRight'){stop();advance();e.preventDefault();}if(e.key==='ArrowLeft'){stop();step=Math.max(0,step-1);render();e.preventDefault();}});render();})();
