(() => {
 const scene=document.getElementById('initiative-scene');if(!scene)return;
 const $=id=>document.getElementById(id);
 const scenarios={
  time:{kind:'TIME · CLOCK REACHES DUE TIME',headline:'13:30 到點，主動查詢',rule:'沒有收到新資料通知，排程仍會啟動檢查。',humanLabel:'看時間：快開會了',human:'快開會了，<br>先確認簡報資料是否最新。',agentLabel:'Time · cron due',agent:'先讀最新報表與會議資料，<br>再判斷需不需要核對。',cue:'Cron due → Read source',input:'Input · current state<br>可能有變化，也可能沒有',evidence:'<span class="time-evidence"><span class="clock-dial" aria-hidden="true"></span><b>13:30</b><small>CHECK DUE</small></span><span class="evidence-calendar"><small>14:00</small><b>Meeting</b><em>會前準備</em></span>',timeline:'<span><b>13:00</b><small>上次檢查</small></span><span class="signal-now"><b>13:30</b><small>Clock tick ↓</small></span><span><b>14:00</b><small>下次檢查</small></span>',outcome:'Time：先到點，再查資料。查完沒有變化，也可以 Skip。'},
  event:{kind:'EVENT · DATA ARRIVES',headline:'新報表送達，觸發 Agent',rule:'觸發來源是 report.updated 這筆事件。',humanLabel:'收到新報表：v2 → v3',human:'報表剛更新！<br>會議簡報可能還是舊版。',agentLabel:'Event · report.updated',agent:'收到報表 v3，簡報仍是 v2。<br>值得先核對差異。',cue:'Webhook → Changed data',input:'Payload · report v3<br>Context · slides v2',evidence:'<span class="evidence-update"><small>REPORT UPDATED</small><span><del>v2</del><i>→</i><b>v3</b></span><em>NEW DATA RECEIVED</em><i class="update-lines"></i></span>',timeline:'<span class="event-source"><small>DATA CHANGE</small><b>Report v3</b></span><span class="event-delivery"><b aria-hidden="true">→</b><small>Webhook</small></span><span class="event-receiver"><small>EVENT RECEIVED</small><b>Agent turn</b></span>',outcome:'Event：先有變動，再喚起。帶著變動內容，判斷是否值得處理。'}
 };
 function render(key){const v=scenarios[key];scene.dataset.cue=key;for(const [id,value] of Object.entries({'trigger-kind':v.kind,'trigger-headline':v.headline,'trigger-rule':v.rule,'human-thought-label':v.humanLabel,'agent-thought-label':v.agentLabel,'agent-cue':v.cue,'trigger-outcome':v.outcome}))$(id).textContent=value;for(const [id,value] of Object.entries({'human-thought':v.human,'agent-thought':v.agent,'agent-input':v.input,'scene-evidence':v.evidence,'trigger-timeline':v.timeline}))$(id).innerHTML=value;$('trigger-timeline').className=key==='time'?'trigger-timeline':'event-transport';$('trigger-timeline').setAttribute('aria-label',v.headline);scene.querySelectorAll('button[data-cue]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cue===key)));}
 scene.querySelectorAll('button[data-cue]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.cue)));
 render(scene.dataset.cue||'event');
})();
