window.PROACTIVITY_STUDY={
  pin:'bb7101c3cfca32ea2982268de47958bea648df98',
  nodes:{
    client:{name:'Interaction Client',cn:'使用者交辦與互動入口',status:'Existing',text:'使用者的 request 形成 Turn。這是 intake；只有把工作交給另一位 agent 或執行者，才適合對照 handoff。',source:'dispatch',links:[['Phase 0.5 · 原始架構','reading/phases/0.5/README.html']]},
    application:{name:'LocalColleagueService',cn:'應用層的接入與生命週期',status:'Existing',text:'interactive 與 automation 共用 admitted work 入口，再進 StandaloneGateway。沿用這條路，不另建一個平行 Runtime Controller。',child:'application',source:'dispatch'},
    ingress:{name:'M365InboundRuntime',cn:'已存在的事件接入',status:'Existing',text:'Microsoft Graph webhook 與 delta polling 進來後，驗證事件、處理 in-flight 重複、查 durable receipt，再送入既有 dispatch。Before 已經有 event-based work。',child:'ingress',source:'inbound'},
    runtime:{name:'OpenClaw',cn:'外部 Runtime Controller',status:'External',text:'應用透過 OpenClawGatewayRuntime 呼叫 /v1/responses。OpenClaw 核心不在此 prototype 實作。此圖選用 managed profile；codex-direct 是另一個 profile，不是下一層。',child:'runtime',source:'adapter',links:[['Agent loop · 官方原詞','https://docs.openclaw.ai/concepts/agent-loop']]},
    state:{name:'Task state + receipts',cn:'已有的任務狀態與收件紀錄',status:'Existing',text:'Task phase、durable receipt、artifact 各有責任。已收件、已執行、已投遞是不同證據；不能因為收到事件就宣告工作完成。',child:'state',source:'events'},
    duties:{name:'Cron / Heartbeat',cn:'情境排程配置',status:'Proposed',text:'採用 OpenClaw 原生 Cron / Heartbeat，配置何時檢查哪個責任。須先確認 prototype 所固定的外部版本與部署 profile 支援的接口；圖中的 native wake 與 next check 是待驗證整合，並非已接好。',links:[['Cron jobs · 官方配置','https://docs.openclaw.ai/cron-jobs'],['Heartbeat · 流程與來源','mechanisms.html#flow-claw-0']]},
    followup:{name:'Follow-up records',cn:'待設計的業務跟進紀錄',status:'Proposed',text:'這是本專案提案，不是 OpenClaw 原生元件。保存責任人、期限、任務關聯、下次檢查條件與成果證據；不要在既有 task phase 偷加 waiting，也不要把尚未回覆當作 completed。',links:[['State · 既有狀態與新增責任','#architecture/after/state']]},
    validation:{name:'Scenario verification',cn:'情境層的驗收',status:'Proposed',text:'注入重複事件、過期資料、取消、重啟與投遞失敗，對照可觀察的工作結果。此頁 demo 是本地說明模型；沒有啟動 OpenClaw 或實際發送 Teams 訊息。',links:[['Verification · 驗證層級','#verification']]},
    dispatch:{name:'dispatch / dispatchAutomation',cn:'不同來源，共用工作接入',status:'Existing',text:'LocalColleagueService 使用 interactive 或 automation 類型呼叫 #withAdmittedWork，再把 Turn 交給 gateway.dispatch。',source:'dispatch'},
    admission:{name:'assertAutomationAdmission',cn:'重新檢查是否允許自動工作',status:'Existing',text:'Provider callback 可使用 fresh readiness check，失敗時拒絕。圖中表示 admission 邊界，並非主張 dispatchAutomation 直接呼叫這個公開方法；dispatchAutomation 的實際入口是 #withAdmittedWork。',source:'admission'},
    gateway:{name:'StandaloneGateway',cn:'同一 thread 排隊，再呼叫 runtime',status:'Existing',text:'以 thread key 管理 promise queue，執行 runtime.respond。這是應用內的順序控制；不是已部署的分散式鎖。distributed gateway 仍為設計 stub。',source:'gateway'},
    adapter:{name:'OpenClawGatewayRuntime',cn:'連接外部執行核心',status:'Existing',text:'將 Turn 轉成 /v1/responses request；可信任的 Microsoft provider turn 使用受限 agent。圖中的原生排程接線仍需另外確認，不因有 HTTP adapter 就視為支援所有 upstream hooks。',source:'adapter'},
    provider:{name:'Graph webhook / delta poll',cn:'外部通知與定期讀取',status:'Existing',text:'Webhook 是 event 入口，delta polling 是時間驅動的 observation。兩種入口可能看見同一件事，所以去重必須跨入口驗證。',source:'inbound'},
    inbound:{name:'M365InboundRuntime.process',cn:'驗證、去重與處理',status:'Existing',text:'先 validateEvent，再 initialize，利用 receipt key 共用進行中的 promise。durable receipt 命中時，恢復 metadata projection 並避免重跑 agent。',source:'inbound'},
    receipts:{name:'M365InboundReceiptStore',cn:'持久化的事件處理證據',status:'Existing',text:'介面提供 has、record、projection、listProjections。紀錄的是 receipt key 與有界限的 metadata；不是完整對話記憶，也不自動等於 exactly-once 外部投遞。',source:'receipts'},
    events:{name:'ProactiveTaskPhase',cn:'現有任務狀態',status:'Existing',text:'received → triaging → awaiting_approval / sending → completed / failed；另有 cancelling、cancelled。箭頭是概念閱讀順序，實際合法轉移由 state guards 決定。沒有 waiting 這個 enum 值。',source:'events'},
    artifacts:{name:'Artifact store',cn:'草稿與可交付內容',status:'Existing',text:'已有 M365 artifact 與 materialize / reply draft 路徑。仍須以具體情境驗證：成果生成後投遞失敗，能否恢復並避免重做副作用。',links:[['Prototype · 實作研究','reading/research/source-notes/colleague-prototype.html']]},
    controller:{name:'OpenClaw /v1/responses',cn:'外部執行控制器',status:'External',text:'Controller 管理 agent execution。原生 Agent loop 是一次 run 內的循環，不代表每個 idle session 都持續呼叫模型。',links:[['Agent loop','https://docs.openclaw.ai/concepts/agent-loop']]},
    harness:{name:'Codex App Server',cn:'此 profile 的執行 harness',status:'External',text:'由 OpenClaw profile 指定的 harness。這是配置中的責任邊界，不能當作此研究已成功驗證整條部署鏈的證據。',links:[['Prototype · Runtime 整合','reading/research/source-notes/colleague-prototype.html']]},
    tools:{name:'Tool execution',cn:'執行讀取或寫入動作',status:'External',text:'Agent loop 可以呼叫工具再接收結果。能執行不代表可任意發訊息；工具範圍、provider 身分與 approval policy 決定可用動作。',links:[['Agent loop','https://docs.openclaw.ai/concepts/agent-loop']]}
  },
  scenarios:[
    {id:'meeting',name:'Meeting preparation',cn:'會前資料準備',time:'14:00',cue:'Cron',question:'下午要開會，資料齊了嗎？',observe:'讀取會議時間、資料清單與已收到的檔案。',action:'有缺件且未問過 → 向指定 owner 追問；齊全 → 整理附來源的 briefing。',chain:['Cron','Tool execution','Task state','Artifact'],mechanisms:['flow-claw-1','flow-claw-0'],existing:'重用 runtime adapter、M365 tools、artifact 與 task state。',delta:'配置會前檢查；新增資料清單、owner、期限與上次追問紀錄。',oracle:'資料齊全時不催件；同一缺件已追問時不重複打擾；briefing 能追到檔案來源。'},
    {id:'progress',name:'Progress check',cn:'專案進度跟進',time:'10:00',cue:'Heartbeat',question:'里程碑快到了，哪件事需要協助？',observe:'查看被授權的專案任務、期限、最後更新與依賴。',action:'有新的阻礙 → 詢問對應負責人；沒有改變 → 保持安靜。',chain:['Heartbeat','Observation','Follow-up records','Delivery'],mechanisms:['flow-claw-0'],existing:'重用 automation admission、既有 provider scope 與 task projection。',delta:'定義 standing duty、阻礙條件、通知頻率與停止條件。',oracle:'沒有改變時不送訊息；同一阻礙只追問適當 owner；任務取消後不再續問。'},
    {id:'mail',name:'Inbound request',cn:'新需求進來',time:'EVENT',cue:'Graph webhook',question:'同事寄來需求，我可以先整理什麼？',observe:'驗證 provider event，辨識 request、附件 metadata 與可讀取範圍。',action:'形成任務與回覆草稿；依 reply policy 等待核准或投遞。',chain:['Graph webhook','M365InboundRuntime','dispatchAutomation','Artifact'],mechanisms:['flow-claw-2'],existing:'已有 M365 event ingress、receipt 與 artifact 路徑；OpenClaw webhook 為比較對象，不等於這條 Microsoft 入口。',delta:'補上國泰業務分類、交付標準及端到端測試 fixture。',oracle:'Webhook 與 polling 同時送同一事件，只執行一次；未授權來源不能取得較高工具權限。'},
    {id:'completion',name:'Completion follow-up',cn:'工作結束後接續下一步',time:'ON EXIT',cue:'on-exit',question:'報表工作跑完了，可以交付了嗎？',observe:'查看 exit status 與產物；程序結束並不等於報表正確。',action:'驗證通過 → 準備交付；驗證失敗 → 保留錯誤與後續處理。',chain:['on-exit','Verification','Artifact','Delivery'],mechanisms:['flow-claw-3','flow-gr-2'],existing:'已有 task state 與 artifact；外部 runtime 的 completion 入口需先驗證 profile 支援。',delta:'绑定受支援的 completion event、產物驗證與重試契約。',oracle:'exit 0 但缺少必要欄位時不得宣告完成；通知失敗不能丟掉已生成成果。'}
  ]
};
