(()=>{
 const deck=document.getElementById('deck'),slides=[...document.querySelectorAll('.slide')],mainCount=slides.filter(s=>!s.classList.contains('appendix')).length;
 const controls=document.querySelector('.presenter-controls'),overview=document.getElementById('overview');
 let displayed=0,requested=0,generation=0,transition=null;
 function fit(){const reserve=document.fullscreenElement?0:controls.offsetHeight+16,scale=Math.max(.01,Math.min(innerWidth/1920,(innerHeight-reserve)/1080));deck.style.transform=`translate(${(innerWidth-1920*scale)/2}px,${Math.max(0,(innerHeight-reserve-1080*scale)/2)}px) scale(${scale})`;}
 function paint(n){displayed=n;slides.forEach((s,i)=>{s.classList.toggle('active',i===n);s.setAttribute('aria-hidden',String(i!==n));s.inert=i!==n;});document.getElementById('counter').textContent=n<mainCount?`${n+1} / ${mainCount}`:`附錄 ${n-mainCount+1} / ${slides.length-mainCount}`;document.getElementById('prev').disabled=n===0;document.getElementById('next').disabled=n===slides.length-1;document.getElementById('appendix').textContent=n<mainCount?'附錄 A':'回主線';document.getElementById('notes-link').href=`speaker-notes.html#slide-${n+1}`;overview.querySelectorAll('[data-slide]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.slide)===n)));history.replaceState(null,'','#'+(n+1));document.title=`${n+1}/${slides.length} · 數位同事主動性`;}
 function show(n,animate=true){const next=Math.max(0,Math.min(slides.length-1,n));if(next===requested&&document.querySelector('.slide.active'))return;requested=next;const ticket=++generation;transition?.skipTransition();const linked=slides[displayed]?.classList.contains('architecture-slide')&&slides[next].classList.contains('architecture-slide');const update=()=>{if(ticket===generation)paint(next)};if(animate&&linked&&document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const t=document.startViewTransition(update);transition=t;t.ready.catch(()=>{});t.finished.catch(()=>{}).finally(()=>{if(transition===t)transition=null})}else update();}
 function openOverview(){if(overview.open){overview.close();return}overview.showModal();overview.querySelector(`[data-slide="${requested}"]`)?.focus();}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.body.requestFullscreen()}catch{document.getElementById('fullscreen').textContent='使用瀏覽器全螢幕'}}
 document.getElementById('prev').onclick=()=>show(requested-1);document.getElementById('next').onclick=()=>show(requested+1);document.getElementById('fullscreen').onclick=fullscreen;document.getElementById('appendix').onclick=()=>show(requested<mainCount?mainCount:mainCount-1);document.getElementById('overview-button').onclick=openOverview;document.getElementById('overview-close').onclick=()=>overview.close();
 overview.querySelectorAll('[data-slide]').forEach(b=>b.onclick=()=>{overview.close();show(Number(b.dataset.slide),false)});
 addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(overview.open){if(e.key.toLowerCase()==='o'){e.preventDefault();overview.close()}return}const k=e.key.toLowerCase();if(k==='o'){e.preventDefault();openOverview()}else if(['ArrowRight','PageDown'].includes(e.key)||(e.key===' '&&!/BUTTON|A/.test(e.target.tagName))){e.preventDefault();show(requested+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(requested-1)}else if(e.key==='Home'){e.preventDefault();show(0)}else if(e.key==='End'){e.preventDefault();show(mainCount-1)}else if(k==='f')fullscreen();else if(k==='a')show(requested<mainCount?mainCount:mainCount-1);else if(k==='n')document.getElementById('notes-link').click();});
 function readHash(){const hash=location.hash.slice(1);const numeric=Number(hash);return /^\d+$/.test(hash)?numeric-1:Math.max(0,slides.findIndex(s=>s.id===hash))}
 addEventListener('resize',fit);addEventListener('fullscreenchange',fit);addEventListener('hashchange',()=>show(readHash(),false));
 window.presentation={go:(n)=>show(n,false),get index(){return requested},get mainCount(){return mainCount},get total(){return slides.length}};
 fit();show(readHash(),false);
})();
