(()=>{
 const deck=document.getElementById('deck'),slides=[...document.querySelectorAll('.slide')],mainCount=slides.filter(s=>!s.classList.contains('appendix')).length;
 let current=0,transition=null;
 function fit(){const reserve=document.fullscreenElement?0:document.querySelector('.presenter-controls').offsetHeight+20;const scale=Math.min(innerWidth/1600,(innerHeight-reserve)/900);deck.style.transform=`scale(${scale})`;deck.style.left=`${(innerWidth-1600*scale)/2}px`;deck.style.top=`${Math.max(0,(innerHeight-reserve-900*scale)/2)}px`;}
 function paint(n){current=n;slides.forEach((s,i)=>{s.classList.toggle('active',i===n);s.setAttribute('aria-hidden',String(i!==n));});document.getElementById('counter').textContent=n<mainCount?`${n+1} / ${mainCount}`:`附錄 ${n-mainCount+1} / ${slides.length-mainCount}`;document.getElementById('prev').disabled=n===0;document.getElementById('next').disabled=n===slides.length-1;document.getElementById('appendix').textContent=n<mainCount?'附錄 A':'回主線';history.replaceState(null,'','#'+(n+1));document.title=`${n+1}/${slides.length} · 數位同事主動性`;}
 function show(n,animate=true){const next=Math.max(0,Math.min(slides.length-1,n));if(next===current&&document.querySelector('.slide.active'))return;transition?.skipTransition();const linked=slides[current]?.classList.contains('architecture-slide')&&slides[next].classList.contains('architecture-slide');if(animate&&linked&&document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches){transition=document.startViewTransition(()=>paint(next));transition.finished.finally(()=>{transition=null;});}else paint(next);}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.body.requestFullscreen();}catch{document.getElementById('fullscreen').textContent='請使用瀏覽器全螢幕';}}
 document.getElementById('prev').onclick=()=>show(current-1);document.getElementById('next').onclick=()=>show(current+1);document.getElementById('fullscreen').onclick=fullscreen;document.getElementById('appendix').onclick=()=>show(current<mainCount?mainCount:mainCount-1);
 addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(current+1);}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(current-1);}else if(e.key==='Home')show(0);else if(e.key==='End')show(mainCount-1);else if(e.key.toLowerCase()==='f')fullscreen();else if(e.key.toLowerCase()==='a')show(current<mainCount?mainCount:mainCount-1);});
 addEventListener('resize',fit);addEventListener('fullscreenchange',fit);addEventListener('hashchange',()=>show((parseInt(location.hash.slice(1))||1)-1,false));fit();show((parseInt(location.hash.slice(1))||1)-1,false);
})();
